version: '2'
services:
  kafka:
    image: spotify/kafkaproxy
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      CONSUMER_THREADS: 1
      TOPICS: test
      ZK_CONNECT: kafka7zookeeper:2181/root/path
      GROUP_ID: kafka